Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2021-08, with the labels that each got.

#17 Add VPA container policy with minAllowed to deployment
  charts/gardener-extension-runtime-gvisor/templates/vpa.yaml
  charts/gardener-extension-runtime-gvisor/values.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#21 Fix containerd config file version detection
  charts/internal/gvisor-installation/templates/configmap-containerd.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#19 [Integration Test] verify if os support gVisor in the cloudprofile
  test/integration/container-runtime/container_runtime.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#23 Disable cache for secrets
  cmd/gardener-extension-runtime-gvisor/app/app.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#22 Update runsc and shim binaries
  Dockerfile
  Makefile
  charts/internal/gvisor-installation/templates/configmap-containerd.yaml
  hack/install-binaries.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/s, merge/squash

#25 Prevent Docker Hub rate limits in the integration test
  test/integration/container-runtime/container_runtime.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/testing
