Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2022-09, with the labels that each got.

#58 Handle `RuntimeClass` `node.k8s.io/v1`
  charts/internal/gvisor/templates/runtimeclass-gvisor.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#59 Use multi-arch image of `busybox`
  test/integration/container-runtime/container_runtime.go
Labels: needs/ok-to-test, needs/review, size/xs

#62 Fix propagation of EFFECTIVE_VERSION during builds in pipeline
  .dockerignore
  Dockerfile
  GVISOR_VERSION
  Makefile
  hack/install-binaries.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#63 Remove support for Shoots with Kubernetes version < 1.17
  charts/internal/gvisor/templates/runtimeclass-gvisor.yaml
  charts/internal/gvisor/values.yaml
  hack/api-reference/config.json
  pkg/charts/charts_test.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
  pkg/controller/controller_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#64 Update alpine version to 3.16.2
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
