Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2023-03, with the labels that each got.

#74 Remove minAllowed.cpu for all components
  charts/gardener-extension-runtime-gvisor/templates/vpa.yaml
  charts/gardener-extension-runtime-gvisor/values.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling

#76 Clean up RBAC rules for `dnsrecords`
  charts/gardener-extension-runtime-gvisor/templates/rbac.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#78 Adapt `NetworkPolicy` rules according to recent refactorings
  charts/gardener-extension-runtime-gvisor/templates/deployment.yaml
  charts/gardener-extension-runtime-gvisor/templates/service.yaml
  example/controller-registration.yaml
Labels: area/dev-productivity, area/networking, area/ops-productivity, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#80 [release-v0.9] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  cmd/gardener-extension-runtime-gvisor/app/app.go
  go.mod
  go.sum
  pkg/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/s

#79 Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  cmd/gardener-extension-runtime-gvisor/app/app.go
  go.mod
  go.sum
  pkg/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/s
