Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2024-11, with the labels that each got.

#150 Bump Gardener dependency to 1.103
  .ci/hack/component_descriptor
  cmd/gardener-extension-runtime-gvisor/app/app.go
  go.mod
  go.sum
  imagevector/imagevector.go
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#149 Cross platform build targets
  Makefile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#154 added net-raw config flag support for gvisor
  GVISOR_VERSION
  Makefile
  README.md
  charts/internal/gvisor-installation/templates/configmap-containerd.yaml
  charts/internal/gvisor-installation/values.yaml
  example/shoot.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/types_client.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/types_client.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/charts/charts_test.go
  pkg/charts/values.go
Labels: kind/api-change, needs/ok-to-test, reviewed/lgtm, size/xl

#155 enable gosec for static code analysis
  .gitignore
  Makefile
  hack/sast.sh
  pkg/apis/config/loader/loader.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s
