Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2025-04, with the labels that each got.

#208 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-runtime-gvisor/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#209 Properly clean up `ManagedResources` during `migrate` phase of control plane migration.
  Makefile
  pkg/controller/actuator.go
  pkg/controller/actuator_delete.go
  pkg/controller/actuator_migrate.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#210 Switch Slack references to Gardener workspace
  .github/ISSUE_TEMPLATE/support.md
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#205 NVIDIA GPUs support via nvproxy
  README.md
  charts/internal/gvisor-installation/values.yaml
  example/shoot.yaml
  pkg/apis/config/v1alpha1/register.go
  pkg/charts/charts_test.go
  pkg/charts/values.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, status/on-hold

#213 Update RBAC permissions in rbac.yaml to refine access controls
  charts/gardener-extension-runtime-gvisor/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/security, kind/technical-debt, needs/ok-to-test, needs/rebase, needs/review, reviewed/lgtm, size/s, status/on-hold
