Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2025-08, with the labels that each got.

#249 chore: remove vendor references from REUSE.toml
  REUSE.toml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xl

#245 Drop support for Shoots with Kubernetes version <= 1.28
  hack/api-reference/config.json
  pkg/controller/controller_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, status/accepted

#252 chore: remove orphaned licenses for REUSE compliance
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  LICENSES/MPL-2.0.txt
Labels: needs/review, needs/second-opinion, reviewed/ok-to-test, size/l

#247 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/s

#272 Add label-based trust to head-update build job pull_request_target builds
  .github/workflows/build.yaml
  .github/workflows/dev_build.yaml
  .github/workflows/non-release.yaml
Labels: area/dev-productivity, kind/regression, needs/review, reviewed/ok-to-test, size/s

#275 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, size/s

#277 ci: fix permission for pull_request_target in conjunction with trusted label
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#270 ci: Periodically bump gVisor version (using cc-utils action)
  .ci/check_and_bump_gvisor_version.py
  .github/workflows/bump-gvisor-version.yaml
  .github/workflows/upgrade-dependencies.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/l, status/accepted
