Repository gardener/gardener-extension-runtime-gvisor, pull requests merged in 2025-03, with the labels that each got.

#151 Drop support for Shoots with Kubernetes version <= 1.26
  charts/gardener-extension-runtime-gvisor/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#199 ImageVectorOverwrite to top level of values file
  charts/gardener-extension-runtime-gvisor/templates/configmap-imagevector-overwrite.yaml
  charts/gardener-extension-runtime-gvisor/templates/deployment.yaml
  charts/gardener-extension-runtime-gvisor/values.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#204 Allow turning on runsc debug logs via providerConfig
  README.md
  charts/internal/gvisor-installation/values.yaml
  pkg/charts/charts_test.go
  pkg/charts/values.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
